### ISSUE TITLE
Python API call failed

### ISSUE THREAD

**Issue by armarbe** [openlumi/homeassistant_on_openwrt#55]
When the installation finished it gave me the following message:
"Installing collected packages: homeassistant
Successfully installed homeassistant-2024.3.3
Done."
I rebooted and checked that both "hass-configurator" and "homeassistant" were enabled. I tried to access to home assistant through port 8123 and didn't load. Then I run hass command through ssh and returned the following text:

ImportError: Error loading shared library libffi.so.8: No such file or directory (needed by /usr/lib/python3.11/site-packages/_cffi_backend.cpython-311-aarch64-linux-musl.so)
thread '<unnamed>' panicked at /builder/shared-workdir/build/sdk/dl/cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.18.3/src/err/mod.rs:790:5:
Python API call failed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/usr/bin/hass", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/homeassistant/__main__.py", line 173, in main
    args = get_arguments()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/homeassistant/__main__.py", line 81, in get_arguments
    from . import config as config_util
  File "/usr/lib/python3.11/site-packages/homeassistant/config.py", line 25, in <module>
    from . import auth
  File "/usr/lib/python3.11/site-packages/homeassistant/auth/__init__.py", line 12, in <module>
    import jwt
  File "/usr/lib/python3.11/site-packages/jwt/__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "/usr/lib/python3.11/site-packages/jwt/api_jwk.py", line 7, in <module>
    from .algorithms import get_default_algorithms, has_crypto, requires_cryptography
  File "/usr/lib/python3.11/site-packages/jwt/algorithms.py", line 12, in <module>
    from .utils import (
  File "/usr/lib/python3.11/site-packages/jwt/utils.py", line 7, in <module>
    from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
  File "/usr/lib/python3.11/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 11, in <module>
  File "/usr/lib/python3.11/site-packages/cryptography/hazmat/_oid.py", line 9, in <module>
pyo3_runtime.PanicException: Python API call failed

**Comment by devbis** [comment]
What openwrt version do you use?

**Comment by armarbe** [comment]
I know it's an older version than it should (21.02), but I updated it to Python 3.11. What more should I update or install? Thank you

**Comment by devbis** [comment]
All python packages in opkg are built for python 3.9. And scripts installs a lot of them.  I doubt that your hack will succeed.
